### ISSUE TITLE
IOException: Sharing violation on path

### ISSUE THREAD

**Issue by SynthKittenDev** [kDanik/heatmap-unity#2]
Hi there!

When using specifically the Character recorder, and not the camera recorder with the 'generate new file if it doesn't exist' causes a sharing violation on path error. This error does not appear for the camera recorder with 'generate new file if it doesn't exist' ticked.

Hope this helps squash a bug!

**Comment by kDanik** [comment]
Hey, thanks for pointing out the issue!

The recorders were creating files and starting recording (=saving data) in the same frame. 
Seems like that was causing such behavior. Now recorders wait for the next frame to start recording, so the issue shouldn't happen anymore.
